import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { ArrowLeft, Search, BookOpen, ShieldAlert, Cpu, Code2, CreditCard, ShieldCheck, AlertOctagon, Scale, Landmark, ChevronRight } from 'lucide-react';

export default function TermsOfServicePage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  const categories = [
    { id: 'all', name: 'All Sections', icon: BookOpen },
    { id: 'accounts', name: 'Accounts & Eligibility', icon: UserCheckIcon, range: [1, 6] },
    { id: 'usage', name: 'Usage & Prohibitions', icon: ShieldAlert, range: [7, 11] },
    { id: 'ai', name: 'AI Heuristics & Training', icon: Cpu, range: [12, 15] }, // 12-15 and 41-43
    { id: 'api', name: 'API & Developer Terms', icon: Code2, range: [16, 20] },
    { id: 'billing', name: 'Billing & Plans', icon: CreditCard, range: [21, 30] },
    { id: 'privacy', name: 'DPDP Privacy & Security', icon: ShieldCheck, range: [31, 40] }, // 31-40 and 44-45
    { id: 'disclaimer', name: 'Warranties & Liability', icon: AlertOctagon, range: [46, 63] },
    { id: 'termination', name: 'Appeals & Infringements', icon: Scale, range: [64, 84] },
    { id: 'governance', name: 'Governance & Contacts', icon: Landmark, range: [85, 92] }
  ];

  // Helper custom icon since lucide-react UserCheck can sometimes fail on specific versions
  function UserCheckIcon(props) {
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <polyline points="16 11 18 13 22 9" />
      </svg>
    );
  }

  const sectionsData = [
    { num: 1, cat: 'accounts', title: 'Introduction', content: 'These Terms constitute a legally binding agreement between you, whether personally or on behalf of an entity ("you", "User", "Customer", or "Data Principal"), and the Company, concerning your access to and use of our platform, APIs, developer portals, websites, RAG infrastructure, and software applications.' },
    { num: 2, cat: 'accounts', title: 'Acceptance of Terms', content: 'By registering, logging into, accessing, or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms, our Privacy Policy, and all applicable laws and regulations. If you do not agree to these Terms, you must immediately cease all access and use of our Services.' },
    { num: 3, cat: 'accounts', title: 'Definitions', content: 'AI Generated Content/Output: Text, summaries, code, files, predictions, embeddings, or other content generated by the Platform\'s LLM components. Input/Prompt: Any text, query, dataset, document, or media provided by the User. Customer Data: All data, text, files, documents, or metadata uploaded or integrated into RAG libraries or databases. Workspace: The logical tenant container environment isolated using PostgreSQL Row-Level Security (RLS) allocated to a Customer. Data Principal: Has the meaning ascribed under the Digital Personal Data Protection (DPDP) Act, 2023.' },
    { num: 4, cat: 'accounts', title: 'Eligibility', content: 'You represent and warrant that you are at least 18 years of age, possess the legal authority to enter into a binding contract under the Indian Contract Act, 1872, and your use does not violate any local, state, national, or international law.' },
    { num: 5, cat: 'accounts', title: 'Account Registration', content: 'You must provide accurate, current, and complete details during signup and safeguard your credentials. Harikson reserves the right to conduct Know-Your-Customer (KYC) verification procedures under applicable anti-money laundering (AML) laws of India and request valid identity/age proof documents.' },
    { num: 6, cat: 'accounts', title: 'User Responsibilities', content: 'You are solely responsible for all activities occurring under your account or team workspace, the legality of Inputs and Customer Data, and establishing robust client-side network parameters.' },
    
    { num: 7, cat: 'usage', title: 'Permitted Uses', content: 'You are granted a non-exclusive, non-transferable, non-sublicensable, revocable, limited license to access and use the Platform for your internal business operations, research, software integration, or personal development.' },
    { num: 8, cat: 'usage', title: 'Prohibited Uses', content: 'You shall not reverse engineer, decompile, or attempt to extract source code, bypass security parameters, perform automated crawling/scraping, attempt prompt injections or jailbreaks, or upload malware and destructive scripts.' },
    { num: 9, cat: 'usage', title: 'AI Usage Policy', content: 'You must not use the Platform to generate deceptive, defamatory, abusive, threatening, or harmful outputs. You must indicate clearly that the content is machine-generated and must not configure AI agents to impersonate real persons.' },
    { num: 10, cat: 'usage', title: 'Acceptable Use Policy', content: 'Under the Information Technology Rules, 2021, you agree not to host, display, or upload any information that belongs to another person without right, is obscene, pedophilic, invasive of privacy, infringes intellectual property, or threatens the sovereignty of India.' },
    { num: 11, cat: 'usage', title: 'User Generated Content', content: 'You retain all rights to content you post on public discussion boards. You grant Harikson a worldwide, royalty-free, perpetual license to host, display, and distribute such content.' },
    
    { num: 12, cat: 'ai', title: 'AI Inputs and Outputs', content: 'The Platform processes Inputs provided by the User and returns corresponding Outputs. You acknowledge that AI systems rely on statistical probabilities and predictive heuristics. Inputs and outputs represent machine-generated text blocks rather than factually audited representations.' },
    { num: 13, cat: 'ai', title: 'Ownership of Input', content: 'You retain all right, title, and intellectual property ownership in and to the Inputs you upload. Harikson claims no ownership over your original queries, documents, or vector data.' },
    { num: 14, cat: 'ai', title: 'Ownership of AI Generated Content', content: 'Subject to subscription compliance, Harikson assigns to you all its rights in the Outputs generated. You are responsible for ensuring the output use does not infringe third-party rights or violate the Copyright Act, 1957.' },
    { num: 15, cat: 'ai', title: 'Intellectual Property Rights', content: 'The Platform, codebase, algorithms, RAG frameworks, user interface designs, logo, trademarks, and documentation are the exclusive property of the Company and its licensors.' },
    
    { num: 16, cat: 'api', title: 'Platform License', content: 'We grant you a limited, non-exclusive, non-sublicensable, revocable license to access the Platform solely through standard web browsers, official developer portals, and approved API endpoints.' },
    { num: 17, cat: 'api', title: 'Third-Party Integrations', content: 'The Platform supports integrations with third-party software, cloud storage providers, and external LLM nodes. You acknowledge that your use is governed by their respective terms and Harikson is not responsible for external database errors.' },
    { num: 18, cat: 'api', title: 'API Usage Terms', content: 'We provide API endpoints for custom integrations. You agree to prevent sharing of private API keys, limit automated calls to plan rate limits, and keep all endpoints isolated under secure TLS links.' },
    { num: 19, cat: 'api', title: 'API Rate Limits', content: 'To maintain stability, we enforce strict API rate limits. You shall not attempt to bypass these limits using proxies or multiple accounts. We reserve the right to throttle connections if necessary.' },
    { num: 20, cat: 'api', title: 'Fair Usage Policy', content: 'We monitor CPU/GPU utilization and vector database queries. If your usage significantly exceeds average utilization metrics of similar plan tiers, we reserve the right to restrict access or transition your workspace to an enterprise tier.' },
    
    { num: 21, cat: 'billing', title: 'Subscription Plans', content: 'We offer Starter, Pro, and Enterprise plan tiers. Each plan allocates distinct capabilities, including message volumes, token limits, RAG vector sizes, and dedicated background queue concurrency slots.' },
    { num: 22, cat: 'billing', title: 'Billing', content: 'You agree to pay the fees associated with your plan. All card transactions and billing procedures comply with RBI mandates for recurring e-mandates. Invoices will be generated electronically in your billing settings.' },
    { num: 23, cat: 'billing', title: 'GST', content: 'Goods and Services Tax (GST) at 18% will be levied on all charges billed to Indian customers. Provide a valid GSTIN to claim input tax credit (ITC).' },
    { num: 24, cat: 'billing', title: 'Taxes', content: 'You are responsible for all other taxes, duties, withholdings, or levies applicable to your transactions in your local jurisdiction.' },
    { num: 25, cat: 'billing', title: 'Auto Renewal', content: 'Subscription plans will automatically renew at the end of the billing period unless cancelled at least 48 hours prior to the renewal date.' },
    { num: 26, cat: 'billing', title: 'Cancellation Policy', content: 'You can cancel your subscription at any time via the self-serve Billing portal. Following cancellation, your subscription status will transition to \'canceling\' and remain active until the end of the current paid billing cycle.' },
    { num: 27, cat: 'billing', title: 'Refund Policy', content: 'Fees paid are non-refundable except as required under the Consumer Protection Act, 2019, or if the billing error was caused solely by a malfunction of our payment processors.' },
    { num: 28, cat: 'billing', title: 'Wallet Credits', content: 'Prepaid wallet credits purchased to cover auxiliary API queries are non-refundable, non-exchangeable, non-transferable, and expire twelve (12) months from the date of purchase.' },
    { num: 29, cat: 'billing', title: 'Promotional Credits', content: 'Promotional or wallet credits have no cash value, cannot be transferred/refunded, expire on the specified date, and can only be applied to billing invoices of the Platform.' },
    { num: 30, cat: 'billing', title: 'Free Trial Terms', content: 'We may offer a free trial plan with usage limits. We reserve the right to terminate free trials at any time without notice.' },
    
    { num: 31, cat: 'privacy', title: 'Enterprise Accounts', content: 'Governed by custom SLAs or Order Forms. Enterprise workspaces feature custom vector limits, Single Sign-On (SSO) integrations, and custom database residency options.' },
    { num: 32, cat: 'privacy', title: 'Team Workspaces', content: 'Allows multiple users to collaborate. The Organization Owner is responsible for the conduct of all Workspace users and guests. Owner and Administrators have access to all Workspace data.' },
    { num: 33, cat: 'privacy', title: 'Organization Ownership', content: 'The user who establishes the Workspace is designated as the Admin/Owner, with full authority to invite users, delete resources, and request database erasure.' },
    { num: 34, cat: 'privacy', title: 'Data Privacy', content: 'Our data collection and processing activities are governed by our Privacy Policy and strictly comply with the Digital Personal Data Protection (DPDP) Act, 2023 of India.' },
    { num: 35, cat: 'privacy', title: 'Data Storage', content: 'All data processed on behalf of Indian customers is stored in secure data centers located within the geographical borders of the Republic of India to comply with local data localization laws.' },
    { num: 36, cat: 'privacy', title: 'Data Security', content: 'We implement commercially reasonable administrative, technical, and physical security measures. You are responsible for maintaining the security of your own network integrations.' },
    { num: 37, cat: 'privacy', title: 'Encryption', content: 'All Customer Data is stored in secure server centers utilizing AES-256 encryption at rest and TLS 1.3 encryption in transit. Database instances are segmented using PostgreSQL Row-Level Security (RLS).' },
    { num: 38, cat: 'privacy', title: 'Data Retention', content: 'We retain your personal and workspace data only for the duration of your active subscription or as required by law. System access and server logs are retained for 180 days per IT Rules 2021.' },
    { num: 39, cat: 'privacy', title: 'Data Deletion', content: 'Upon account cancellation or tenant termination, we purge vectors, files, and chat records from active databases within 30 days. Backups are overwritten within a maximum window of 90 days.' },
    { num: 40, cat: 'privacy', title: 'User Data Export', content: 'You can download or export your conversation history and index metrics in JSON format from the Settings console prior to requesting workspace deletion.' },
    { num: 41, cat: 'privacy', title: 'AI Model Training Policy', content: 'Harikson maintains strict separation between your databases and the base AI models. We do not use your private vectors or files for training baseline neural nodes.' },
    { num: 42, cat: 'privacy', title: 'Whether user content is used for model training', content: 'Harikson does NOT use your Inputs, Customer Data, prompts, or vectors to train or fine-tune public foundation language models.' },
    { num: 43, cat: 'privacy', title: 'User Opt-Out Policy', content: 'By default, all customer workspaces are opt-out environments. Any metadata training or telemetry analysis for model refinement requires explicit, separate, affirmative consent.' },
    { num: 44, cat: 'privacy', title: 'Confidential Information', content: 'Each party agrees to protect the other\'s proprietary non-public technical, product, and financial information ("Confidential Information") with a reasonable degree of care.' },
    { num: 45, cat: 'privacy', title: 'Security Responsibilities', content: 'You are responsible for client-side firewall configurations, security audits, and protecting API tokens. Harikson is not liable for security compromises arising from weak user credentials.' },
    
    { num: 46, cat: 'disclaimer', title: 'Platform Availability', content: 'We target an uptime of 99.9% for our cloud APIs, but do not guarantee uninterrupted platform availability. You are advised to implement client-side fallback configurations.' },
    { num: 47, cat: 'disclaimer', title: 'Maintenance Windows', content: 'We conduct scheduled platform maintenance during off-peak hours (usually IST). We will post system notices on the user dashboard at least twenty-four (24) hours prior.' },
    { num: 48, cat: 'disclaimer', title: 'Service Interruptions', content: 'While we strive to maintain 99.9% uptime, we do not guarantee uninterrupted access. Scheduled maintenance windows will occur during off-peak hours (IST) and will be announced via the dashboard status pages.' },
    { num: 49, cat: 'disclaimer', title: 'Beta Features', content: 'Beta features are experimental and may exhibit bugs or service failures. Use of Beta features is entirely at your own risk and provided "AS IS".' },
    { num: 50, cat: 'disclaimer', title: 'Experimental AI Features', content: 'We may introduce experimental or "Beta" LLM nodes. These are provided "AS IS" without any warranties, uptime SLAs, or support commitments.' },
    { num: 51, cat: 'disclaimer', title: 'Third-Party AI Models', content: 'Our platform allows you to access third-party LLMs (e.g., GPT, Claude, Gemini). By configuring your system to connect to these models, you agree to comply with the terms and usage policies of their respective providers.' },
    { num: 52, cat: 'disclaimer', title: 'Third-Party Services Disclaimer', content: 'If we utilize public API infrastructure from providers like OpenAI, Anthropic, or Google, you acknowledge that their operational constraints, pricing adjustments, or licensing modifications may affect the Platform\'s operations.' },
    { num: 53, cat: 'disclaimer', title: 'Accuracy of AI Output', content: 'AI models generate text based on statistical prediction. We make no warranty or representation regarding the correctness, validity, completeness, or suitability of any Output.' },
    { num: 54, cat: 'disclaimer', title: 'Human Verification Requirement', content: 'Outputs are generated by predictive text algorithms and may occasionally contain factual inaccuracies or hallucinations. You must perform independent human verification on all outputs.' },
    { num: 55, cat: 'disclaimer', title: 'High-Risk Use Restrictions', content: 'You shall not use the Platform for life-critical activities, medical diagnostics, weapon design, nuclear facilities control, or automated legal contracts.' },
    { num: 56, cat: 'disclaimer', title: 'Medical Disclaimer', content: 'The Platform does not provide medical advice or diagnosis.' },
    { num: 57, cat: 'disclaimer', title: 'Financial Disclaimer', content: 'No outputs from the Platform constitute financial, stock trading, or investment advice.' },
    { num: 58, cat: 'disclaimer', title: 'Legal Advice Disclaimer', content: 'The Platform is not a licensed attorney and does not generate binding legal advice.' },
    { num: 59, cat: 'disclaimer', title: 'Educational Disclaimer', content: 'All instructional material is for educational purposes only.' },
    { num: 60, cat: 'disclaimer', title: 'AI Hallucination Disclaimer', content: 'You acknowledge that LLM outputs can be unpredictable and agree to hold Harikson harmless for damages resulting from incorrect AI predictions or hallucinations.' },
    { num: 61, cat: 'disclaimer', title: 'Limitation of Liability', content: 'TO THE MAXIMUM EXTENT PERMITTED BY THE CONSUMER PROTECTION ACT, 2019 AND OTHER LAWS OF INDIA, HARIKSON\'S TOTAL LIABILITY SHALL NOT EXCEED THE TOTAL FEES PAID BY YOU IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT.' },
    { num: 62, cat: 'disclaimer', title: 'Disclaimer of Warranties', content: 'THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE COMPANY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.' },
    { num: 63, cat: 'disclaimer', title: 'Indemnification', content: 'You agree to indemnify, defend, and hold harmless Harikson, its directors, and officers from and against any claims, losses, or damages arising from your violation of these Terms or your Customer Data.' },
    
    { num: 64, cat: 'termination', title: 'Suspension of Accounts', content: 'We reserve the right to temporarily suspend your user account or workspace if we suspect a security breach, unauthorized API traffic patterns, or if subscription payments are overdue by more than seven (7) business days.' },
    { num: 65, cat: 'termination', title: 'Termination', content: 'We reserve the right to suspend or terminate your account immediately for violation of these Terms, the Acceptable Use Policy, or a legal directive from an Indian government authority.' },
    { num: 66, cat: 'termination', title: 'Appeals Process', content: 'If your account is suspended, you may request a review by emailing appeals@harikson.ai within fourteen (14) business days of the suspension notice.' },
    { num: 67, cat: 'termination', title: 'Abuse Reporting', content: 'If you detect any platform activity that violates our acceptable use rules or represents abusive behavior, you can submit an abuse report to abuse@harikson.ai.' },
    { num: 68, cat: 'termination', title: 'Copyright Complaints', content: 'If you believe that any material on the Platform infringes your intellectual property, you may submit a takedown request to our Grievance Officer in writing, containing details required under the Copyright Act, 1957.' },
    { num: 69, cat: 'termination', title: 'DMCA-like Procedure adapted for India', content: 'Under Section 52(1)(c) of the Indian Copyright Act, 1957, you must submit a signed affidavit containing proof of ownership of the copyrighted work, identification of the infringing url, and your contact details.' },
    { num: 70, cat: 'termination', title: 'Trademark Complaints', content: 'In the event of suspected trademark misuse on our public dashboards or API registries, please email details of the registered trademark certificate and URL locations of the infringement to legal@harikson.ai.' },
    { num: 71, cat: 'termination', title: 'Notice and Takedown Procedure', content: 'Upon receipt of a valid infringement notice, we will remove or disable access to the infringing material within 36 hours and notify the affected user.' },
    { num: 72, cat: 'termination', title: 'Force Majeure', content: 'Neither party will be liable for failure to perform obligations due to events beyond their control (e.g., acts of God, war, acts of terrorism, civil unrest, grid failures, government embargoes).' },
    { num: 73, cat: 'termination', title: 'Export Compliance', content: 'You represent that you will not use, transport, or export software code or access tokens in violation of the Foreign Trade (Development and Regulation) Act, 1992 of India.' },
    { num: 74, cat: 'termination', title: 'Sanctions Compliance', content: 'You represent and warrant that you are not located in a sanctioned country, or listed on any government embargo or restricted party list (including Indian, US, and EU lists).' },
    { num: 75, cat: 'termination', title: 'Governing Law (India)', content: 'These Terms shall be governed by and construed in accordance with the laws of the Republic of India.' },
    { num: 76, cat: 'termination', title: 'Jurisdiction (Specify Indian city)', content: 'Any dispute, legal proceeding, or litigation arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Noida, Uttar Pradesh, India.' },
    { num: 77, cat: 'termination', title: 'Arbitration under the Arbitration and Conciliation Act, 1996', content: 'Any dispute arising out of or in connection with this Agreement shall be referred to arbitration in Noida, India. The arbitration shall be conducted in accordance with the Arbitration and Conciliation Act, 1996, by a sole arbitrator appointed mutually.' },
    { num: 78, cat: 'termination', title: 'Consumer Rights', content: 'Nothing in these Terms shall limit your consumer rights under the Consumer Protection Act, 2019.' },
    { num: 79, cat: 'termination', title: 'Severability', content: 'If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force.' },
    { num: 80, cat: 'termination', title: 'Waiver', content: 'No waiver of any term of these Terms shall be deemed a further or continuing waiver.' },
    { num: 81, cat: 'termination', title: 'Assignment', content: 'You may not assign your rights under these Terms without our prior written consent. The Company may assign its rights under these Terms at its sole discretion.' },
    { num: 82, cat: 'termination', title: 'Survival', content: 'Provisions regarding intellectual property ownership, limitations of liability, disclaimers, governing law, and dispute resolution shall survive the termination of this Agreement.' },
    { num: 83, cat: 'termination', title: 'Entire Agreement', content: 'These Terms, together with our Privacy Policy, constitute the entire agreement between you and Harikson regarding your use of the Platform.' },
    { num: 84, cat: 'termination', title: 'Changes to Terms', content: 'We may update these Terms from time to time. When we do, we will publish the updated version on this page and notify you via email or platform notification.' },
    
    { num: 85, cat: 'governance', title: 'Contact Information', content: 'For corporate governance inquiries, you can reach out directly to our support desk at support@harikson.ai.' },
    { num: 86, cat: 'governance', title: 'Grievance Officer details (as required under Indian law)', content: 'Under the Information Technology Act, 2000 and the DPDP Act, 2023, the Grievance Officer details are: Name: Ashish Pratap Singh Tomar, Email: grievance@harikson.ai, Address: Sector 62, Noida, Uttar Pradesh, India - 201301.' },
    { num: 87, cat: 'governance', title: 'Compliance Officer details (placeholder)', content: 'Compliance Officer contact: compliance@harikson.ai' },
    { num: 88, cat: 'governance', title: 'Nodal Officer details (placeholder)', content: 'Nodal Officer contact: nodal@harikson.ai' },
    { num: 89, cat: 'governance', title: 'Registered Office details (placeholder)', content: 'Address: Harikson AI Technologies Private Limited, Sector 62, Noida, Uttar Pradesh, India - 201301' },
    { num: 90, cat: 'governance', title: 'Support Contact', content: 'Support desk: support@harikson.ai' },
    { num: 91, cat: 'governance', title: 'Effective Date', content: 'Date: July 19, 2026' },
    { num: 92, cat: 'governance', title: 'Version History', content: 'v1.0.0: Initial Release (July 19, 2026)' }
  ];

  // Filter sections by search query and category tab
  const filteredSections = sectionsData.filter(sec => {
    const matchesCategory = activeCategory === 'all' || sec.cat === activeCategory;
    const matchesSearch = searchQuery === '' || 
      sec.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      sec.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
      `section ${sec.num}`.includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div style={{
      backgroundColor: '#f8fafc',
      color: '#1e293b',
      minHeight: '100vh',
      fontFamily: "'Outfit', sans-serif"
    }}>
      <Head>
        <title>Terms of Service | Harikson AI Platform</title>
        <meta name="description" content="Harikson AI Terms of Service - comprehensive agreement compliant with Indian and global regulations." />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </Head>

      {/* Top Banner Gradient Hero */}
      <div style={{
        background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 50%, #60a5fa 100%)',
        color: '#ffffff',
        padding: '80px 20px 120px 20px',
        textAlign: 'center',
        position: 'relative',
        boxShadow: 'inset 0 -30px 40px rgba(0,0,0,0.03)'
      }}>
        <div style={{
          position: 'absolute',
          top: '25px',
          left: '20px'
        }}>
          <Link href="/">
            <a style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px',
              color: 'rgba(255, 255, 255, 0.85)',
              textDecoration: 'none',
              fontSize: '14.5px',
              fontWeight: '500',
              background: 'rgba(255, 255, 255, 0.1)',
              padding: '6px 14px',
              borderRadius: '20px',
              backdropFilter: 'blur(8px)',
              transition: 'background 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.2)'}
            onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.1)'}
            >
              <ArrowLeft size={16} />
              Back to Home
            </a>
          </Link>
        </div>

        <h1 style={{
          fontSize: '48px',
          fontWeight: '800',
          margin: '0 0 16px 0',
          letterSpacing: '-0.75px',
          textShadow: '0 2px 4px rgba(0,0,0,0.1)'
        }}>
          Terms of Service
        </h1>
        <p style={{
          fontSize: '18px',
          color: 'rgba(255,255,255,0.9)',
          maxWidth: '700px',
          margin: '0 auto',
          lineHeight: '1.6',
          fontWeight: '300'
        }}>
          Clear, transparent, and binding legal guidelines governing your workspace nodes, vector directories, and custom API usage on Harikson.
        </p>

        {/* Floating Search Container */}
        <div style={{
          position: 'absolute',
          bottom: '-30px',
          left: '50%',
          transform: 'translateX(-50%)',
          width: '90%',
          maxWidth: '650px',
          background: '#ffffff',
          borderRadius: '30px',
          padding: '4px 8px 4px 20px',
          display: 'flex',
          alignItems: 'center',
          boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.05)',
          border: '1px solid #e2e8f0'
        }}>
          <Search size={20} color="#94a3b8" style={{ marginRight: '10px' }} />
          <input
            type="text"
            placeholder="Search across 92 legal sections (e.g. GST, RLS, DPO...)"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{
              border: 'none',
              outline: 'none',
              width: '100%',
              fontSize: '15px',
              color: '#1e293b',
              padding: '10px 0'
            }}
          />
          {searchQuery && (
            <button 
              onClick={() => setSearchQuery('')}
              style={{
                background: 'none',
                border: 'none',
                color: '#94a3b8',
                cursor: 'pointer',
                marginRight: '10px',
                fontSize: '13px'
              }}
            >
              Clear
            </button>
          )}
        </div>
      </div>

      {/* Main Container Layout */}
      <div style={{
        maxWidth: '1200px',
        margin: '60px auto 100px auto',
        padding: '0 20px',
        display: 'flex',
        gap: '40px',
        flexWrap: 'wrap'
      }}>
        {/* Sidebar Table of Contents */}
        <div style={{
          flex: '1 1 280px',
          position: 'relative'
        }}>
          <div style={{
            position: 'sticky',
            top: '40px',
            background: '#ffffff',
            border: '1px solid #e2e8f0',
            borderRadius: '16px',
            padding: '24px 16px',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,0.02)'
          }}>
            <h3 style={{
              fontSize: '14px',
              fontWeight: '700',
              color: '#64748b',
              textTransform: 'uppercase',
              letterSpacing: '1px',
              margin: '0 0 16px 8px'
            }}>
              Table of Contents
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              {categories.map(cat => {
                const Icon = cat.icon;
                const isActive = activeCategory === cat.id;
                return (
                  <button
                    key={cat.id}
                    onClick={() => setActiveCategory(cat.id)}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '10px',
                      width: '100%',
                      background: isActive ? '#f0f6ff' : 'none',
                      border: 'none',
                      color: isActive ? '#1d4ed8' : '#475569',
                      padding: '10px 14px',
                      borderRadius: '8px',
                      textAlign: 'left',
                      cursor: 'pointer',
                      fontSize: '14px',
                      fontWeight: isActive ? '600' : '400',
                      transition: 'all 0.2s'
                    }}
                    onMouseEnter={(e) => {
                      if (!isActive) e.currentTarget.style.background = '#f8fafc';
                    }}
                    onMouseLeave={(e) => {
                      if (!isActive) e.currentTarget.style.background = 'none';
                    }}
                  >
                    <Icon size={18} color={isActive ? '#1d4ed8' : '#94a3b8'} />
                    <span style={{ flex: 1 }}>{cat.name}</span>
                    <ChevronRight size={14} style={{
                      opacity: isActive ? 1 : 0,
                      transform: isActive ? 'translateX(0)' : 'translateX(-4px)',
                      transition: 'all 0.2s'
                    }} />
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div style={{
          flex: '3 1 600px'
        }}>
          {/* Metadata banner */}
          <div style={{
            background: '#ffffff',
            border: '1px solid #e2e8f0',
            borderRadius: '16px',
            padding: '20px 24px',
            marginBottom: '30px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            boxShadow: '0 4px 6px -1px rgba(0,0,0,0.02)'
          }}>
            <div>
              <span style={{ color: '#64748b', fontSize: '13px' }}>Corporate Registry:</span>
              <div style={{ fontSize: '14px', fontWeight: '600', color: '#1e293b', marginTop: '2px' }}>
                Harikson AI Technologies Pvt. Ltd. (CIN: U72900UP2026PTC123456)
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <span style={{ color: '#64748b', fontSize: '13px' }}>Version:</span>
              <div style={{ fontSize: '14px', fontWeight: '600', color: '#1e293b', marginTop: '2px' }}>
                v1.0.0 (Effective)
              </div>
            </div>
          </div>

          {/* Sections List */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {filteredSections.length > 0 ? (
              filteredSections.map(sec => (
                <div
                  key={sec.num}
                  id={`section-${sec.num}`}
                  style={{
                    background: '#ffffff',
                    border: '1px solid #e2e8f0',
                    borderRadius: '16px',
                    padding: '24px 30px',
                    boxShadow: '0 4px 6px -1px rgba(0,0,0,0.02)',
                    transition: 'transform 0.2s, box-shadow 0.2s'
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-2px)';
                    e.currentTarget.style.boxShadow = '0 10px 15px -3px rgba(0, 0, 0, 0.05)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = '0 4px 6px -1px rgba(0,0,0,0.02)';
                  }}
                >
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    marginBottom: '12px'
                  }}>
                    <span style={{
                      fontSize: '13px',
                      fontWeight: '700',
                      background: '#eff6ff',
                      color: '#2563eb',
                      padding: '4px 10px',
                      borderRadius: '6px'
                    }}>
                      Section {sec.num}
                    </span>
                    <h3 style={{
                      fontSize: '18px',
                      fontWeight: '700',
                      color: '#0f172a',
                      margin: 0
                    }}>
                      {sec.title}
                    </h3>
                  </div>
                  <p style={{
                    fontSize: '15px',
                    lineHeight: '1.75',
                    color: '#475569',
                    margin: 0
                  }}>
                    {sec.content}
                  </p>
                </div>
              ))
            ) : (
              <div style={{
                background: '#ffffff',
                border: '1px solid #e2e8f0',
                borderRadius: '16px',
                padding: '60px 20px',
                textAlign: 'center',
                boxShadow: '0 4px 6px -1px rgba(0,0,0,0.02)'
              }}>
                <Search size={40} color="#94a3b8" style={{ marginBottom: '16px' }} />
                <h4 style={{ fontSize: '18px', color: '#1e293b', margin: '0 0 8px 0' }}>No Sections Found</h4>
                <p style={{ color: '#64748b', fontSize: '14px', margin: 0 }}>
                  We couldn&apos;t find any terms matching &ldquo;{searchQuery}&rdquo;. Try using another query term.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
